config/routes.rb
Rails.application.routes.draw do
  resources :galeria
  get 'menu' => 'menu#index'

  resources :mensajes
  resources :nosotros
  resources :servicios
  resources :frases
  resources :cervezas
   get 'consultas/index'

  get 'index/home'
  post "/" => "static#create"

  root 'index#home'

  get 'contact' => 'index#contacto'

  get 'nueva_consulta' => 'index#nueva_consulta'
  post 'index/home' => 'index#home'
  post 'consulta' => 'index#create'

end

app/models/cerveza.rb
class Cerveza < ActiveRecord::Base
end

app/models/consulta.rb
class Consultas

  attr_accessor :nombre, :mail, :consulta

  def initialize(nombre, mail, consulta)
  	@nombre = nombre || ""
  	@mail = mail || ""
  	@consulta = consulta || ""
  end

end

app/models/frase.rb
class Frase < ActiveRecord::Base
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
end

app/models/nosotro.rb
class Nosotro < ActiveRecord::Base
end

app/models/persona.rb
class Persona
	include ActiveModel::Model

	attr_accessor :name, :mail, :consulta

	#validates :name, :mail, :consulta, presence: true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/controllers/cervezas_controller.rb
class CervezasController < ApplicationController
  before_action :set_cerveza, only: [:show, :edit, :update, :destroy]

  # GET /cervezas
  # GET /cervezas.json
  def index
    @cervezas = Cerveza.all
  end

  # GET /cervezas/1
  # GET /cervezas/1.json
  def show
  end

  # GET /cervezas/new
  def new
    @cerveza = Cerveza.new
  end

  # GET /cervezas/1/edit
  def edit
  end

  # POST /cervezas
  # POST /cervezas.json
  def create
    @cerveza = Cerveza.new(cerveza_params)

    respond_to do |format|
      if @cerveza.save
        format.html { redirect_to @cerveza, notice: 'Cerveza was successfully created.' }
        format.json { render :show, status: :created, location: @cerveza }
      else
        format.html { render :new }
        format.json { render json: @cerveza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cervezas/1
  # PATCH/PUT /cervezas/1.json
  def update
    respond_to do |format|
      if @cerveza.update(cerveza_params)
        format.html { redirect_to @cerveza, notice: 'Cerveza was successfully updated.' }
        format.json { render :show, status: :ok, location: @cerveza }
      else
        format.html { render :edit }
        format.json { render json: @cerveza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cervezas/1
  # DELETE /cervezas/1.json
  def destroy
    @cerveza.destroy
    respond_to do |format|
      format.html { redirect_to cervezas_url, notice: 'Cerveza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cerveza
      @cerveza = Cerveza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cerveza_params
      params.require(:cerveza).permit(:marca, :nombre, :descripcion, :stock)
    end
end

app/controllers/frases_controller.rb
class FrasesController < ApplicationController
  before_action :set_frase, only: [:show, :edit, :update, :destroy]

  # GET /frases
  # GET /frases.json
  def index
    @frases = Frase.all
  end

  # GET /frases/1
  # GET /frases/1.json
  def show
  end

  # GET /frases/new
  def new
    @frase = Frase.new
  end

  # GET /frases/1/edit
  def edit
  end

  # POST /frases
  # POST /frases.json
  def create
    @frase = Frase.new(frase_params)

    respond_to do |format|
      if @frase.save
        format.html { redirect_to @frase, notice: 'Frase was successfully created.' }
        format.json { render :show, status: :created, location: @frase }
      else
        format.html { render :new }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frases/1
  # PATCH/PUT /frases/1.json
  def update
    respond_to do |format|
      if @frase.update(frase_params)
        format.html { redirect_to @frase, notice: 'Frase was successfully updated.' }
        format.json { render :show, status: :ok, location: @frase }
      else
        format.html { render :edit }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frases/1
  # DELETE /frases/1.json
  def destroy
    @frase.destroy
    respond_to do |format|
      format.html { redirect_to frases_url, notice: 'Frase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frase
      @frase = Frase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frase_params
      params.require(:frase).permit(:frase)
    end
end

app/controllers/galeria_controller.rb
class GaleriaController < ApplicationController
  before_action :set_galerium, only: [:show, :edit, :update, :destroy]

  # GET /galeria
  # GET /galeria.json
  def index
    @galeria = Galerium.all
  end

  # GET /galeria/1
  # GET /galeria/1.json
  def show
  end

  # GET /galeria/new
  def new
    @galerium = Galerium.new
  end

  # GET /galeria/1/edit
  def edit
  end

  # POST /galeria
  # POST /galeria.json
  def create
    @galerium = Galerium.new(galerium_params)

    respond_to do |format|
      if @galerium.save
        format.html { redirect_to @galerium, notice: 'Galerium was successfully created.' }
        format.json { render :show, status: :created, location: @galerium }
      else
        format.html { render :new }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria/1
  # PATCH/PUT /galeria/1.json
  def update
    respond_to do |format|
      if @galerium.update(galerium_params)
        format.html { redirect_to @galerium, notice: 'Galerium was successfully updated.' }
        format.json { render :show, status: :ok, location: @galerium }
      else
        format.html { render :edit }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria/1
  # DELETE /galeria/1.json
  def destroy
    @galerium.destroy
    respond_to do |format|
      format.html { redirect_to galeria_url, notice: 'Galerium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galerium
      @galerium = Galerium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galerium_params
      params.require(:galerium).permit(:foto, :foto_numero)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]
  def home
    @cervezas = Cerveza.all
    @frases = Frase.all
    @nosotros = Nosotro.all
    @servicios = Servicio.all
    @galerias = Galerium.all
  end
  def new
  	@consultas = Persona.new
  end

  def create
    @consultas = Persona.new(params[:consulta])
    if @consultas.valid?
      # TODO send message here
      enviar_mail(@consultas)
      Mensaje.create!({name: @consultas.name, mail: @consultas.mail, consulta: @consultas.consulta})
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      redirect_to root_url, notice: "Something goes wrong.."
    end
  end

  def enviar_mail(consulta)
  	UserMailer.mailer(consulta).deliver_now
    UserMailer.mail_beer(consulta).deliver_now
  end

  private

  def contacto_params
  	params.require(:contact).permit(:name, :mail, :consulta)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cervezas_helper.rb
module CervezasHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/frases_helper.rb
module FrasesHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/cervezas/_form.html.erb
<%= form_for(@cerveza) do |f| %>
  <% if @cerveza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cerveza.errors.count, "error") %> prohibited this cerveza from being saved:</h2>

      <ul>
      <% @cerveza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.check_box :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cervezas/edit.html.erb
<h1>Editing Cerveza</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cerveza %> |
<%= link_to 'Atras', cervezas_path %>

app/views/cervezas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cervezas</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Foto</th>
      <th>Descripcion</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cervezas.each do |cerveza| %>
      <tr>
        <td><%= cerveza.marca %></td>
        <td><img style="width: 100px; height: 100px;"src=<%= cerveza.foto %>/></td>
        <td><%= cerveza.descripcion %></td>
        <td><%= cerveza.stock %></td>
        <td><%= link_to 'Mostrar', cerveza %></td>
        <td><%= link_to 'Editar', edit_cerveza_path(cerveza) %></td>
        <td><%= link_to 'Eliminar', cerveza, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Cerveza', new_cerveza_path %>
<%= link_to 'Menu', menu_path %>

app/views/cervezas/new.html.erb
<h1>New Cerveza</h1>

<%= render 'form' %>

<%= link_to 'Atras', cervezas_path %>

app/views/cervezas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @cerveza.marca %>
</p>

<img src=
  <%= @cerveza.foto %>/>

<p>
  <strong>Descripcion:</strong>
  <%= @cerveza.descripcion %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @cerveza.stock %>
</p>

<%= link_to 'Editar', edit_cerveza_path(@cerveza) %> |
<%= link_to 'Atras', cervezas_path %>