config/routes.rb
Rails.application.routes.draw do
  resources :galeria
  get 'menu' => 'menu#index'

  resources :mensajes
  resources :nosotros
  resources :servicios
  resources :frases
  resources :cervezas
   get 'consultas/index'

  get 'index/home'
  post "/" => "static#create"

  root 'index#home'

  get 'contact' => 'index#contacto'

  get 'nueva_consulta' => 'index#nueva_consulta'
  post 'index/home' => 'index#home'
  post 'consulta' => 'index#create'

end

app/models/cerveza.rb
class Cerveza < ActiveRecord::Base
end

app/models/consulta.rb
class Consultas

  attr_accessor :nombre, :mail, :consulta

  def initialize(nombre, mail, consulta)
  	@nombre = nombre || ""
  	@mail = mail || ""
  	@consulta = consulta || ""
  end

end

app/models/frase.rb
class Frase < ActiveRecord::Base
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
end

app/models/nosotro.rb
class Nosotro < ActiveRecord::Base
end

app/models/persona.rb
class Persona
	include ActiveModel::Model

	attr_accessor :name, :mail, :consulta

	#validates :name, :mail, :consulta, presence: true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/controllers/frases_controller.rb
class FrasesController < ApplicationController
  before_action :set_frase, only: [:show, :edit, :update, :destroy]

  # GET /frases
  # GET /frases.json
  def index
    @frases = Frase.all
  end

  # GET /frases/1
  # GET /frases/1.json
  def show
  end

  # GET /frases/new
  def new
    @frase = Frase.new
  end

  # GET /frases/1/edit
  def edit
  end

  # POST /frases
  # POST /frases.json
  def create
    @frase = Frase.new(frase_params)

    respond_to do |format|
      if @frase.save
        format.html { redirect_to @frase, notice: 'Frase was successfully created.' }
        format.json { render :show, status: :created, location: @frase }
      else
        format.html { render :new }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frases/1
  # PATCH/PUT /frases/1.json
  def update
    respond_to do |format|
      if @frase.update(frase_params)
        format.html { redirect_to @frase, notice: 'Frase was successfully updated.' }
        format.json { render :show, status: :ok, location: @frase }
      else
        format.html { render :edit }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frases/1
  # DELETE /frases/1.json
  def destroy
    @frase.destroy
    respond_to do |format|
      format.html { redirect_to frases_url, notice: 'Frase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frase
      @frase = Frase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frase_params
      params.require(:frase).permit(:frase)
    end
end

app/controllers/galeria_controller.rb
class GaleriaController < ApplicationController
  before_action :set_galerium, only: [:show, :edit, :update, :destroy]

  # GET /galeria
  # GET /galeria.json
  def index
    @galeria = Galerium.all
  end

  # GET /galeria/1
  # GET /galeria/1.json
  def show
  end

  # GET /galeria/new
  def new
    @galerium = Galerium.new
  end

  # GET /galeria/1/edit
  def edit
  end

  # POST /galeria
  # POST /galeria.json
  def create
    @galerium = Galerium.new(galerium_params)

    respond_to do |format|
      if @galerium.save
        format.html { redirect_to @galerium, notice: 'Galerium was successfully created.' }
        format.json { render :show, status: :created, location: @galerium }
      else
        format.html { render :new }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria/1
  # PATCH/PUT /galeria/1.json
  def update
    respond_to do |format|
      if @galerium.update(galerium_params)
        format.html { redirect_to @galerium, notice: 'Galerium was successfully updated.' }
        format.json { render :show, status: :ok, location: @galerium }
      else
        format.html { render :edit }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria/1
  # DELETE /galeria/1.json
  def destroy
    @galerium.destroy
    respond_to do |format|
      format.html { redirect_to galeria_url, notice: 'Galerium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galerium
      @galerium = Galerium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galerium_params
      params.require(:galerium).permit(:foto, :foto_numero)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]
  def home
    @cervezas = Cerveza.all
    @frases = Frase.all
    @nosotros = Nosotro.all
    @servicios = Servicio.all
    @galerias = Galerium.all
  end
  def new
  	@consultas = Persona.new
  end

  def create
    @consultas = Persona.new(params[:consulta])
    if @consultas.valid?
      # TODO send message here
      enviar_mail(@consultas)
      Mensaje.create!({name: @consultas.name, mail: @consultas.mail, consulta: @consultas.consulta})
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      redirect_to root_url, notice: "Something goes wrong.."
    end
  end

  def enviar_mail(consulta)
  	UserMailer.mailer(consulta).deliver_now
    UserMailer.mail_beer(consulta).deliver_now
  end

  private

  def contacto_params
  	params.require(:contact).permit(:name, :mail, :consulta)
  end
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]

  # GET /mensajes
  # GET /mensajes.json
  def index
    @mensajes = Mensaje.all
  end

  # GET /mensajes/1
  # GET /mensajes/1.json
  def show
  end

  # GET /mensajes/new
  def new
    @mensaje = Mensaje.new
  end

  # GET /mensajes/1/edit
  def edit
  end

  # POST /mensajes
  # POST /mensajes.json
  def create
    @mensaje = Mensaje.new(mensaje_params)

    respond_to do |format|
      if @mensaje.save
        format.html { redirect_to @mensaje, notice: 'Mensaje was successfully created.' }
        format.json { render :show, status: :created, location: @mensaje }
      else
        format.html { render :new }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensajes/1
  # PATCH/PUT /mensajes/1.json
  def update
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        format.html { redirect_to @mensaje, notice: 'Mensaje was successfully updated.' }
        format.json { render :show, status: :ok, location: @mensaje }
      else
        format.html { render :edit }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensajes/1
  # DELETE /mensajes/1.json
  def destroy
    @mensaje.destroy
    respond_to do |format|
      format.html { redirect_to mensajes_url, notice: 'Mensaje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensaje
      @mensaje = Mensaje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensaje_params
      params.require(:mensaje).permit(:name, :mail, :consulta)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cervezas_helper.rb
module CervezasHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/frases_helper.rb
module FrasesHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/mensajes/_form.html.erb
<%= form_for(@mensaje) do |f| %>
  <% if @mensaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensaje.errors.count, "error") %> prohibited this mensaje from being saved:</h2>

      <ul>
      <% @mensaje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :consulta %><br>
    <%= f.text_field :consulta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mensajes/edit.html.erb
<h1>Editing Mensaje</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @mensaje %> |
<%= link_to 'Atras', mensajes_path %>

app/views/mensajes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mensajes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Mail</th>
      <th>Consulta</th>
      <th>Creado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mensajes.each do |mensaje| %>
      <tr>
        <td><%= mensaje.name %></td>
        <td><%= mensaje.mail %></td>
        <td><%= mensaje.consulta %></td>
        <td><%= mensaje.created_at %></td>
        <td><%= link_to 'Mostrar', mensaje %></td>
        <td><%= link_to 'Editar', edit_mensaje_path(mensaje) %></td>
        <td><%= link_to 'Eliminar', mensaje, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Mensaje', new_mensaje_path %>
<%= link_to 'Menu', menu_path %>

app/views/mensajes/new.html.erb
<h1>Nuevo Mensaje</h1>

<%= render 'form' %>

<%= link_to 'Atras', mensajes_path %>

app/views/mensajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @mensaje.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @mensaje.mail %>
</p>

<p>
  <strong>Consulta:</strong>
  <%= @mensaje.consulta %>
</p>

<%= link_to 'Editar', edit_mensaje_path(@mensaje) %> |
<%= link_to 'Atras', mensajes_path %>