config/routes.rb
Rails.application.routes.draw do
  resources :galeria
  get 'menu' => 'menu#index'

  resources :mensajes
  resources :nosotros
  resources :servicios
  resources :frases
  resources :cervezas
   get 'consultas/index'

  get 'index/home'
  post "/" => "static#create"

  root 'index#home'

  get 'contact' => 'index#contacto'

  get 'nueva_consulta' => 'index#nueva_consulta'
  post 'index/home' => 'index#home'
  post 'consulta' => 'index#create'

end

app/models/cerveza.rb
class Cerveza < ActiveRecord::Base
end

app/models/consulta.rb
class Consultas

  attr_accessor :nombre, :mail, :consulta

  def initialize(nombre, mail, consulta)
  	@nombre = nombre || ""
  	@mail = mail || ""
  	@consulta = consulta || ""
  end

end

app/models/frase.rb
class Frase < ActiveRecord::Base
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
end

app/models/nosotro.rb
class Nosotro < ActiveRecord::Base
end

app/models/persona.rb
class Persona
	include ActiveModel::Model

	attr_accessor :name, :mail, :consulta

	#validates :name, :mail, :consulta, presence: true
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/controllers/frases_controller.rb
class FrasesController < ApplicationController
  before_action :set_frase, only: [:show, :edit, :update, :destroy]

  # GET /frases
  # GET /frases.json
  def index
    @frases = Frase.all
  end

  # GET /frases/1
  # GET /frases/1.json
  def show
  end

  # GET /frases/new
  def new
    @frase = Frase.new
  end

  # GET /frases/1/edit
  def edit
  end

  # POST /frases
  # POST /frases.json
  def create
    @frase = Frase.new(frase_params)

    respond_to do |format|
      if @frase.save
        format.html { redirect_to @frase, notice: 'Frase was successfully created.' }
        format.json { render :show, status: :created, location: @frase }
      else
        format.html { render :new }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frases/1
  # PATCH/PUT /frases/1.json
  def update
    respond_to do |format|
      if @frase.update(frase_params)
        format.html { redirect_to @frase, notice: 'Frase was successfully updated.' }
        format.json { render :show, status: :ok, location: @frase }
      else
        format.html { render :edit }
        format.json { render json: @frase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frases/1
  # DELETE /frases/1.json
  def destroy
    @frase.destroy
    respond_to do |format|
      format.html { redirect_to frases_url, notice: 'Frase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frase
      @frase = Frase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frase_params
      params.require(:frase).permit(:frase)
    end
end

app/controllers/galeria_controller.rb
class GaleriaController < ApplicationController
  before_action :set_galerium, only: [:show, :edit, :update, :destroy]

  # GET /galeria
  # GET /galeria.json
  def index
    @galeria = Galerium.all
  end

  # GET /galeria/1
  # GET /galeria/1.json
  def show
  end

  # GET /galeria/new
  def new
    @galerium = Galerium.new
  end

  # GET /galeria/1/edit
  def edit
  end

  # POST /galeria
  # POST /galeria.json
  def create
    @galerium = Galerium.new(galerium_params)

    respond_to do |format|
      if @galerium.save
        format.html { redirect_to @galerium, notice: 'Galerium was successfully created.' }
        format.json { render :show, status: :created, location: @galerium }
      else
        format.html { render :new }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria/1
  # PATCH/PUT /galeria/1.json
  def update
    respond_to do |format|
      if @galerium.update(galerium_params)
        format.html { redirect_to @galerium, notice: 'Galerium was successfully updated.' }
        format.json { render :show, status: :ok, location: @galerium }
      else
        format.html { render :edit }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria/1
  # DELETE /galeria/1.json
  def destroy
    @galerium.destroy
    respond_to do |format|
      format.html { redirect_to galeria_url, notice: 'Galerium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galerium
      @galerium = Galerium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galerium_params
      params.require(:galerium).permit(:foto, :foto_numero)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]
  def home
    @cervezas = Cerveza.all
    @frases = Frase.all
    @nosotros = Nosotro.all
    @servicios = Servicio.all
    @galerias = Galerium.all
  end
  def new
  	@consultas = Persona.new
  end

  def create
    @consultas = Persona.new(params[:consulta])
    if @consultas.valid?
      # TODO send message here
      enviar_mail(@consultas)
      Mensaje.create!({name: @consultas.name, mail: @consultas.mail, consulta: @consultas.consulta})
      redirect_to root_url, notice: "Message sent! Thank you for contacting us."
    else
      redirect_to root_url, notice: "Something goes wrong.."
    end
  end

  def enviar_mail(consulta)
  	UserMailer.mailer(consulta).deliver_now
    UserMailer.mail_beer(consulta).deliver_now
  end

  private

  def contacto_params
  	params.require(:contact).permit(:name, :mail, :consulta)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cervezas_helper.rb
module CervezasHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/frases_helper.rb
module FrasesHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/frases/_form.html.erb
<%= form_for(@frase) do |f| %>
  <% if @frase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frase.errors.count, "error") %> prohibited this frase from being saved:</h2>

      <ul>
      <% @frase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :frase %><br>
    <%= f.text_field :frase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frases/edit.html.erb
<h1>Editar Frase</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @frase %> |
<%= link_to 'Atras', frases_path %>

app/views/frases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Frases</h1>

<table>
  <thead>
    <tr>
      <th>Frase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frases.each do |frase| %>
      <tr>
        <td><%= frase.frase %></td>
        <td><%= link_to 'Mostrar', frase %></td>
        <td><%= link_to 'Editar', edit_frase_path(frase) %></td>
        <td><%= link_to 'Eliminar', frase, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Frase', new_frase_path %>
<%= link_to 'Menu', menu_path %>

app/views/frases/new.html.erb
<h1>Nueva Frase</h1>

<%= render 'form' %>

<%= link_to 'Atras', frases_path %>

app/views/frases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frase:</strong>
  <%= @frase.frase %>
</p>

<%= link_to 'Editar', edit_frase_path(@frase) %> |
<%= link_to 'Atras', frases_path %>

app/views/galeria/_form.html.erb
<%= form_for(@galerium) do |f| %>
  <% if @galerium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galerium.errors.count, "error") %> prohibited this galerium from being saved:</h2>

      <ul>
      <% @galerium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
    <div class="field">
    <%= f.label :foto_numero %><br>
    <%= f.text_field :foto_numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galeria/edit.html.erb
<h1>Editar Galeria</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @galerium %> |
<%= link_to 'Atras', galeria_path %>

app/views/galeria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galeria</h1>

<table>
  <thead>
    <tr>
      <th>Foto</th>
      <th>Foto_numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galeria.each do |galerium| %>
      <tr>
        <td><%= galerium.foto %></td>
        <td><%= galerium.foto_numero %></td>
        <td><%= link_to 'Mostrar', galerium %></td>
        <td><%= link_to 'Editar', edit_galerium_path(galerium) %></td>
        <td><%= link_to 'Elimiar', galerium, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Imagen', new_galerium_path %>
<%= link_to 'Menu', menu_path %>

app/views/galeria/new.html.erb
<h1>Nueva Foto</h1>

<%= render 'form' %>

<%= link_to 'Atras', galeria_path %>

app/views/galeria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foto:</strong>
  <%= @galerium.foto %>
</p>
<p>
  <strong>Foto:</strong>
  <%= @galerium.foto_numero %>
</p>

<%= link_to 'Editar', edit_galerium_path(@galerium) %> |
<%= link_to 'Atras', galeria_path %>

app/views/menu/index.html.erb
<head>
	<meta charset='utf-8'/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>	
<h1>The Craft Beer Truck menu</h1>


<div class= "container">
	<div class="row">
		<div class="col-md-4">
			<%= link_to image_tag("http://alternativeberlin.com/cms/uploads/2014/03/Picture-1-Via-beerwrangler2.jpg", :border => 0), :action => 'index', :controller => 'cervezas', :class => 'dock-item' %><h2> Cervezas </h2>
		</div>
		<div class="col-md-4">
			<%= link_to image_tag("http://onegoaradio.com/wp-content/uploads/2015/11/Contact-us-keyboard-key.jpg", :border => 0), :action => 'index', :controller => 'mensajes', :class => 'dock-item' %>
			<h2>Mensajes</h2>
		</div>
		<div class="col-md-4">
			<%= link_to image_tag("http://blog4businessowners.com/wp-content/uploads/2014/12/Who-are-we.jpg", :border => 0), :action => 'index', :controller => 'nosotros', :class => 'dock-item'%>
			<h2>Nosotros</h2>
		</div>
		<div class="col-md-4">
			<%= link_to image_tag("http://www.tapitdraughtservice.com/images/Refined/draught-image.jpg", :border => 0), :action => 'index', :controller => 'servicios', :class => 'dock-item' %>
			<h2>Servicios</h2>
		</div>
		
		<div class="col-md-4">
			<%= link_to image_tag('https://secure.static.tumblr.com/d53c817fa7cf86dbfdab9c61bea8c713/xbfrde5/wIqnhevpi/tumblr_static_tumblr_static_2u19aldw77s4kk80ogsksgwg0_640.png', :border => 0), :action => 'index', :controller => 'frases', :class => 'dock-item'  %>
			<h2>Frases</h2>
		</div>
		<div class="col-md-4">
			<%= link_to image_tag('http://www.brevardnc.org/wp-content/uploads/2015/07/redot-fine-art-gallery.jpg' , :border => 0), :action => 'index', :controller => 'galeria', :class => 'dock-item'%>
			<h2>Galeria</h2>
		</div>
</div>